### ISSUE TITLE
Running Flasky on Port 443, Mail confirmation no longer works.

### ISSUE THREAD

**Issue by jacobmammoliti** [miguelgrinberg/flasky#147] opened 2016-05-23 20:04 UTC
When I run my Flasy app on Flask default port 5000, the email confirmation token works perfectly. However, I am now running my on Nginx with Gunicorn and running on port 443 and now the email confirmation no longer works. I receieve the emails to my email but when I click the click, it still says not verified.

Any Ideas?

**Comment by miguelgrinberg** [comment] 2016-05-23 21:12
Is the link in the email correct?

**Comment by jacobmammoliti** [comment] 2016-05-23 22:00
Yes it is, at least, I believe it is right. http://ipaddress/auth/confirm/...... Only thing that this link doesn't have is the :5000 port number after the IP

**Comment by miguelgrinberg** [comment] 2016-05-23 22:00
http or https?

**Comment by jacobmammoliti** [comment] 2016-05-23 22:06
I tried both and neither worked

**Comment by miguelgrinberg** [comment] 2016-05-23 22:08
Next thing would be to check if the HTTP requests make it all the way to the server. Have you verified that the Flask endpoint that handles the confirmation is called?

**Comment by jacobmammoliti** [comment] 2016-05-23 22:16
I haven't and I'm not sure how to verify that. Could you point me in the direction to do this?

**Comment by miguelgrinberg** [comment] 2016-05-23 22:23
There are different ways to do that. You can add a print statement in the function, or run inside a debugger and set a breakpoint there.

If you find that the function isn't called, then the routing between your components is not correctly set up. You may need to look at the nginx and gunicorn configuration. If on the other side, the function is called, you need to debug the function and find why it decides the given token is invalid.

**Comment by jacobmammoliti** [comment] 2016-05-23 23:12
When I click on the link received in the email, the page shows "You have confirmed your account. Thanks!" As well as the "You have not confirmed your account yet." dialog. Could this mean that the function is indeed called and its just not validating the token properly?
I just find this weird because when I run it on port 5000, everything works.

**Comment by miguelgrinberg** [comment] 2016-05-23 23:18
@jacobmammoliti Take a look at this issue: https://github.com/miguelgrinberg/flasky/issues/58. I think it matches your description. A temporary solution is to downgrade gunicorn to 18.0. But this is a Flask bug which is already fixed towards the next release, whenever that might happen.

**Comment by jacobmammoliti** [comment] 2016-05-24 00:33
This worked thank you!

**Comment by miguelgrinberg** [comment] 2016-05-24 06:00
Awesome, then I'll close this as a duplicate of #58.

**Closed by miguelgrinberg** 2016-05-24 06:00 UTC
