### ISSUE TITLE
Flasky automatically login a new user as an existing user

### ISSUE THREAD

**Issue by harrywang** [miguelgrinberg/flasky#71] opened 2015-09-09 16:08 UTC
I think this is a major bug/problem - I have tested on a few different machines. To reproduce:

1. Login as an admin, i.e., Admin (you can either keep the page open or close the page)
2. Register a new user, i.e., User 1
3. Click the "To confirm your account please click here." link in the confirmation email
4. a new web page is opened with Admin logged in (not the new user). 

The correct way should be a confirmation page or login page for the new user. 

@miguelgrinberg any idea why this is happening? Thanks!

**Comment by miguelgrinberg** [comment] 2015-09-09 16:11
How do you register a new user while logged in as admin?

**Comment by harrywang** [comment] 2015-09-09 16:16
To clarify: 

I did 1 in Safari, did 2 in Chrome on the same Mac, did 3 in Mac Mail, and Safari opens for 4.

**Comment by miguelgrinberg** [comment] 2015-09-09 16:21
Okay, good.

This is not a bug, really. Your Safari is logged in as admin, so in that state it is not possible to confirm another user's account. If you open the confirmation link Flasky will not be able to validate it, as it does not match the logged in user.

For the account confirmation to work you will need to log out from the admin account, log in as the new user and then click the confirmation link. Alternatively, you can log out from admin, then click the confirmation link, and you in that case you will automatically be asked to log in as the new user.

**Comment by harrywang** [comment] 2015-09-09 19:36
Thanks, @miguelgrinberg

**Comment by harrywang** [comment] 2015-09-10 15:31
@miguelgrinberg I tried the following and think this issue is still valid:

1. login as admin in Safari, did not choose "keep me logged in", then close Safari
2. open Chrome, click reset password "click here to reset it", enter another user's email address (user 1 not admin).
3. in the reset password email for user 1, click "To reset your password click here."
4. Safari is opened with admin logged in showing the index page

I tried the same workflow on Facebook using two different accounts, after 3, a login page is presented instead of automatically logging in the first user. More specific question is: how to tell the current request from an email with a token is for a user that is not the current user? Hope I explained this clearly. Thanks.

**Comment by miguelgrinberg** [comment] 2015-09-10 15:43
> login as admin in Safari, did not choose "keep me logged in", then close Safari

When you say that you "closed" Safari, did you close the entire browser of just the tab? Session cookies remain active until the browser process is closed, so closing a tab and reopening does not clear the logged in user. This is a standard browser behavior, implemented by all browsers, as far as I know.

> how to tell the current request from an email with a token is for a user that is not the current user?

Flasky can easily tell when you click on a token that is not for the current user. That is why it ignores the token if it isn't address to the current user. It seems you would prefer that the current user is logged out and then the user for which the token is for be logged in. You can certainly implement that behavior if you like it better. I personally don't think it is a good idea that if user A is logged in and then an action taken by user B can force user A to be logged out. My preference is that if user A is logged in and user B is not, then A has more priority, so requests from B are ignored.

**Comment by harrywang** [comment] 2015-09-10 15:48
I only closed the tab - so you are right - when I close the browser, the problem is gone. Could you please provide more details on How "Flasky can easily tell when you click on a token that is not for the current user."? Any file in Flasky has that part implemented? Thanks a lot.

**Comment by miguelgrinberg** [comment] 2015-09-10 15:56
So this is done differently depending on which kind of token is being used.

For the account confirmation token, there is a `current_user.confirm(token)` call. Inside the `confirm()` method, the user id stored in the token is compared against `self.id` and if they don't match the token is considered invalid (see [here](https://github.com/miguelgrinberg/flasky/blob/master/app/models.py#L153)). The change email token is handled in a similar way.

For the password reset token, it is required that the user is not logged in, because obviously if the user is logged in it would not need a password reset. So in this case any logged in user would prevent the token from validating (see [here](https://github.com/miguelgrinberg/flasky/blob/master/app/auth/views.py#L124-L125)).

**Comment by harrywang** [comment] 2015-09-10 16:12
@miguelgrinberg thanks a lot for your help!!!

**Closed** 2016-06-01 16:24 UTC
Labels: invalid
